/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelperRouteImport } from './routes/helper'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminHelpersRouteImport } from './routes/admin.helpers'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRequestIdRouteImport } from './routes/dashboard.request.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperRoute = HelperRouteImport.update({
  id: '/helper',
  path: '/helper',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/dashboard/new',
  path: '/dashboard/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/dashboard/history',
  path: '/dashboard/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHelpersRoute = AdminHelpersRouteImport.update({
  id: '/admin/helpers',
  path: '/admin/helpers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRequestIdRoute = DashboardRequestIdRouteImport.update({
  id: '/dashboard/request/$id',
  path: '/dashboard/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/helper': typeof HelperRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/request/$id': typeof DashboardRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/helper': typeof HelperRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/request/$id': typeof DashboardRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/helper': typeof HelperRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/request/$id': typeof DashboardRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/helper'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/new'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/admin/users'
    | '/admin/helpers'
    | '/admin/tasks'
    | '/forgot-password'
    | '/terms'
    | '/privacy'
    | '/dashboard/request/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/helper'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/new'
    | '/dashboard/profile'
    | '/dashboard'
    | '/admin/users'
    | '/admin/helpers'
    | '/admin/tasks'
    | '/forgot-password'
    | '/terms'
    | '/privacy'
    | '/dashboard/request/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/helper'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/new'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/admin/users'
    | '/admin/helpers'
    | '/admin/tasks'
    | '/forgot-password'
    | '/terms'
    | '/privacy'
    | '/dashboard/request/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HelperRoute: typeof HelperRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminHelpersRoute: typeof AdminHelpersRoute
  AdminTasksRoute: typeof AdminTasksRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  TermsRoute: typeof TermsRoute
  PrivacyRoute: typeof PrivacyRoute
  DashboardRequestIdRoute: typeof DashboardRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper': {
      id: '/helper'
      path: '/helper'
      fullPath: '/helper'
      preLoaderRoute: typeof HelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/dashboard/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/helpers': {
      id: '/admin/helpers'
      path: '/admin/helpers'
      fullPath: '/admin/helpers'
      preLoaderRoute: typeof AdminHelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/request/$id': {
      id: '/dashboard/request/$id'
      path: '/dashboard/request/$id'
      fullPath: '/dashboard/request/$id'
      preLoaderRoute: typeof DashboardRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HelperRoute: HelperRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminHelpersRoute: AdminHelpersRoute,
  AdminTasksRoute: AdminTasksRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  TermsRoute: TermsRoute,
  PrivacyRoute: PrivacyRoute,
  DashboardRequestIdRoute: DashboardRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
