name: Build and deploy Node.js app to Azure Web App - suruhin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install, build, and test
        run: |
          npm install --legacy-peer-deps
          npm run build:azure
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D91333FFCDC9437C81848B374281A009 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FDCFCD5AD855423AA975C14F26D8E7B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_740E84F95C5F41F9807E577F483C311E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "suruhin"
          slot-name: "Production"
          package: .
